### ISSUE TITLE
Possible Mod incompatability?

### ISSUE THREAD

**Issue by SigDrox** [Funwayguy/EnviroMine#121]
The server is running forge-1.7.10-10.13.2.1230 and the problem only has occurred when enviromine is present, the crash report seems to point towards something called an classenumerator and the funwaymodauthentication.

The exact output is:
at enviromine.utils.ClassEnumerator.loadClass(ClassEnumerator.java:16)
at enviromine.utils.ClassEnumerator.processJarfile(ClassEnumerator.java:78)
at enviromine.core.FunwayModAuthentication.UnlockClasses(FunwayModAuthentication.java:190)
at enviromine.core.FunwayModAuthentication.CheckAndUnlockMod(FunwayModAuthentication.java:69)
at enviromine.core.EnviroMine.preInit(EnviroMine.java:69)

Any suggestions?

**Comment by Funwayguy** [comment]
What version of EnviroMine are you using and please post the FULL report (use pastebin if necessary)

**Comment by SigDrox** [comment]
version 1.3.104

http://pastebin.com/etZscGQq
