### ISSUE TITLE
Please See this and fix it.

### ISSUE THREAD

**Issue by DPxKnightxZero** [Funwayguy/EnviroMine#161]
// Why is it breaking :(

Time: 10/4/15 2:03 PM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: 4
	at net.minecraft.entity.player.InventoryPlayer.func_70301_a(InventoryPlayer.java:577)
	at infiniteinvo.inventory.SlotLockable.func_75211_c(SlotLockable.java:41)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:201)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.player.InventoryPlayer.func_70301_a(InventoryPlayer.java:577)
	at infiniteinvo.inventory.SlotLockable.func_75211_c(SlotLockable.java:41)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:201)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)

-- Screen render details --
Details:
	Screen name: codechicken.nei.GuiExtendedCreativeInv
	Mouse location: Scaled: (497, 177). Absolute: (995, 302)
	Screen size: Scaled: (640, 329). Absolute: (1280, 657). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['P3rf3ct_Zer0'/1996, l='MpServer', x=-167.50, y=73.62, z=825.50]]
	Chunk stats: MultiplayerChunkCache: 169, 178
	Level seed: 0
	Level generator: ID 05 - Highlands, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-167,64,818), Chunk: (at 9,4,2 in -11,51; contains blocks -176,0,816 to -161,255,831), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 1216 game time, 1216 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 124 total; [EntitySpider['Spider'/74763, l='MpServer', x=-184.53, y=34.00, z=812.84], EntitySpider['Spider'/74764, l='MpServer', x=-189.84, y=35.00, z=806.66], EntityItem['item.tile.gravel'/39020, l='MpServer', x=-140.81, y=29.13, z=772.78], EntityCryptZombie['Crypt Zombie'/213122, l='MpServer', x=-194.76, y=36.00, z=799.87], EntityCryptZombie['Crypt Zombie'/213124, l='MpServer', x=-206.58, y=35.00, z=795.42], EntitySquid['Squid'/4251, l='MpServer', x=-131.81, y=46.31, z=831.31], EntitySquid['Squid'/39074, l='MpServer', x=-142.43, y=54.33, z=786.71], EntitySquid['Squid'/34989, l='MpServer', x=-140.50, y=44.00, z=819.50], EntitySquid['Squid'/3274, l='MpServer', x=-142.88, y=54.43, z=773.34], EntityBat['Bat'/143564, l='MpServer', x=-188.06, y=37.73, z=875.84], EntitySkeleton['Skeleton'/192725, l='MpServer', x=-197.03, y=27.00, z=788.34], EntityItem['item.tile.rail'/300274, l='MpServer', x=-153.88, y=32.13, z=768.88], EntityItem['item.item.dyePowder.black'/225563, l='MpServer', x=-185.13, y=64.13, z=788.09], EntitySkeleton['Skeleton'/20794, l='MpServer', x=-168.41, y=36.00, z=824.94], EntityItem['item.tile.gravel'/249152, l='MpServer', x=-104.50, y=16.30, z=764.50], EntityTrail['unknown'/84304, l='MpServer', x=-167.50, y=73.62, z=825.50], EntityItem['item.item.dyePowder.black'/123228, l='MpServer', x=-207.66, y=57.13, z=787.78], EntityItem['item.tile.gravel'/44395, l='MpServer', x=-133.22, y=24.13, z=812.81], EntityItem['item.tile.gravel'/219571, l='MpServer', x=-105.50, y=16.13, z=764.47], EntityBat['Bat'/187883, l='MpServer', x=-123.28, y=24.50, z=870.63], EntityItem['item.tile.waterKelpGiantGRN'/507, l='MpServer', x=-228.81, y=51.13, z=771.72], EntityItem['item.tile.waterKelpGiantGRN'/508, l='MpServer', x=-230.56, y=51.13, z=771.66], EntityItem['item.tile.waterKelpGiantGRN'/509, l='MpServer', x=-228.78, y=52.13, z=771.97], EntityItem['item.tile.waterKelpGiantGRN'/511, l='MpServer', x=-227.69, y=52.13, z=772.53], EntityItem['item.tile.waterKelpGiantGRN'/512, l='MpServer', x=-228.81, y=49.13, z=769.66], EntityItem['item.tile.waterKelpGiantGRN'/515, l='MpServer', x=-230.97, y=48.13, z=766.66], EntityZombie['Zombie'/25111, l='MpServer', x=-179.50, y=35.00, z=814.50], EntityMinecartChest['entity.MinecartChest.name'/549, l='MpServer', x=-190.50, y=27.52, z=786.50], EntityMinecartChest['entity.MinecartChest.name'/566, l='MpServer', x=-187.50, y=13.52, z=903.50], EntityItem['item.item.reeds'/568, l='MpServer', x=-193.94, y=63.13, z=886.81], EntityItem['item.item.reeds'/569, l='MpServer', x=-192.06, y=63.13, z=886.94], EntityItem['item.item.reeds'/570, l='MpServer', x=-195.41, y=63.13, z=885.25], EntityItem['item.item.dyePowder.black'/31290, l='MpServer', x=-177.91, y=55.13, z=789.28], EntityMinecartChest['entity.MinecartChest.name'/571, l='MpServer', x=-199.50, y=19.36, z=905.50], EntityItem['item.tile.mushroom10'/585, l='MpServer', x=-176.59, y=23.13, z=764.31], EntityMinecartChest['entity.MinecartChest.name'/587, l='MpServer', x=-173.50, y=9.36, z=886.50], EntityBat['Bat'/44620, l='MpServer', x=-127.34, y=47.00, z=792.31], EntityMinecartChest['entity.MinecartChest.name'/596, l='MpServer', x=-155.50, y=28.52, z=758.50], EntityMinecartChest['entity.MinecartChest.name'/597, l='MpServer', x=-163.50, y=22.52, z=754.50], EntityMinecartChest['entity.MinecartChest.name'/598, l='MpServer', x=-164.50, y=37.52, z=756.50], EntityBat['Bat'/147040, l='MpServer', x=-179.50, y=33.10, z=848.50], EntityMinecartChest['entity.MinecartChest.name'/613, l='MpServer', x=-164.50, y=32.52, z=771.50], EntityItem['item.tile.torch'/614, l='MpServer', x=-158.94, y=28.13, z=776.84], EntityItem['item.tile.mushroom7'/615, l='MpServer', x=-158.28, y=28.13, z=784.81], EntityItem['item.tile.mushroom7'/616, l='MpServer', x=-151.19, y=22.13, z=783.19], EntityItem['item.tile.waterKelpGiantGRN'/617, l='MpServer', x=-168.13, y=49.13, z=777.41], EntityItem['item.tile.waterKelpGiantGRN'/618, l='MpServer', x=-167.97, y=49.13, z=778.72], EntityItem['item.tile.waterKelpGiantGRN'/619, l='MpServer', x=-169.09, y=49.13, z=776.97], EntityItem['item.tile.waterKelpGiantGRN'/620, l='MpServer', x=-166.66, y=49.13, z=779.84], EntityItem['item.tile.waterKelpGiantGRN'/621, l='MpServer', x=-168.53, y=49.13, z=775.38], EntityItem['item.tile.waterKelpGiantGRN'/622, l='MpServer', x=-168.19, y=49.13, z=773.94], EntityItem['item.tile.waterKelpGiantGRN'/623, l='MpServer', x=-165.81, y=48.13, z=776.88], EntityItem['item.tile.waterKelpGiantGRN'/624, l='MpServer', x=-169.38, y=49.13, z=773.28], EntityItem['item.tile.waterKelpGiantGRN'/625, l='MpServer', x=-167.19, y=49.13, z=777.16], EntityItem['item.tile.torch'/626, l='MpServer', x=-166.47, y=36.13, z=813.72], EntityKobold['Kobold'/91782, l='MpServer', x=-167.46, y=32.00, z=795.32], EntityItem['item.tile.gravel'/45711, l='MpServer', x=-124.22, y=26.13, z=810.19], EntityItem['item.tile.waterKelpGiantGRN'/664, l='MpServer', x=-150.25, y=50.13, z=772.78], EntityItem['item.tile.waterKelpGiantGRN'/665, l='MpServer', x=-151.44, y=49.13, z=772.81], EntityItem['item.tile.waterKelpGiantGRN'/666, l='MpServer', x=-151.28, y=50.13, z=771.22], EntityItem['item.tile.waterKelpGiantGRN'/667, l='MpServer', x=-151.81, y=48.13, z=774.19], EntityItem['item.tile.waterKelpGiantGRN'/668, l='MpServer', x=-153.25, y=49.13, z=771.38], EntityItem['item.tile.waterKelpGiantGRN'/669, l='MpServer', x=-150.69, y=51.13, z=771.53], EntityItem['item.tile.waterKelpGiantGRN'/670, l='MpServer', x=-152.81, y=49.13, z=772.84], EntityItem['item.tile.waterKelpGiantYEL'/672, l='MpServer', x=-149.38, y=48.13, z=777.56], EntityItem['item.tile.waterKelpGiantYEL'/673, l='MpServer', x=-149.63, y=49.13, z=776.63], EntityItem['item.tile.waterKelpGiantYEL'/674, l='MpServer', x=-149.22, y=48.13, z=778.75], EntityItem['item.tile.waterKelpGiantYEL'/675, l='MpServer', x=-152.41, y=48.13, z=777.81], EntityCreeper['Creeper'/52899, l='MpServer', x=-195.56, y=37.00, z=801.03], EntityMinecartChest['entity.MinecartChest.name'/676, l='MpServer', x=-140.50, y=32.52, z=770.50], EntityItem['item.item.string'/677, l='MpServer', x=-144.81, y=32.13, z=778.44], EntityItem['item.item.string'/678, l='MpServer', x=-144.69, y=32.13, z=776.41], EntityItem['item.tile.grassSeaOats'/680, l='MpServer', x=-153.88, y=65.13, z=819.75], EntityItem['item.tile.waterKelpGiantYEL'/695, l='MpServer', x=-138.81, y=47.13, z=832.03], EntityItem['item.tile.gravel'/150201, l='MpServer', x=-152.78, y=28.13, z=782.19], EntitySquid['Squid'/263881, l='MpServer', x=-207.50, y=60.21, z=792.09], EntityItem['item.item.dyePowder.black'/29390, l='MpServer', x=-130.00, y=52.13, z=811.13], EntityHuman['Blorph'/298721, l='MpServer', x=-130.50, y=32.00, z=841.50], EntityItem['item.item.string'/745, l='MpServer', x=-105.91, y=14.00, z=769.20], EntityItem['item.tile.mushroom10'/747, l='MpServer', x=-102.81, y=27.13, z=763.13], EntityItem['item.tile.waterKelpGiantGRN'/748, l='MpServer', x=-115.84, y=48.13, z=773.09], EntityItem['item.tile.waterKelpGiantGRN'/749, l='MpServer', x=-117.69, y=48.13, z=773.38], EntityItem['item.tile.waterKelpGiantGRN'/750, l='MpServer', x=-119.78, y=48.13, z=772.19], EntityItem['item.tile.waterKelpGiantGRN'/751, l='MpServer', x=-126.16, y=53.13, z=786.81], EntityItem['item.tile.waterKelpGiantGRN'/752, l='MpServer', x=-127.31, y=52.13, z=784.97], EntityItem['item.tile.waterKelpGiantGRN'/753, l='MpServer', x=-125.72, y=54.13, z=787.75], EntitySkeleton['Skeleton'/197362, l='MpServer', x=-175.13, y=32.00, z=799.50], EntityItem['item.tile.waterKelpGiantGRN'/755, l='MpServer', x=-127.22, y=53.13, z=788.16], EntityItem['item.tile.waterKelpGiantGRN'/756, l='MpServer', x=-126.38, y=47.13, z=835.47], EntityItem['item.tile.waterKelpGiantGRN'/757, l='MpServer', x=-128.66, y=47.13, z=835.19], EntityItem['item.tile.waterKelpGiantGRN'/758, l='MpServer', x=-128.03, y=46.13, z=831.63], EntityItem['item.tile.gravel'/142069, l='MpServer', x=-153.50, y=28.13, z=782.75], EntityItem['item.tile.waterKelpGiantGRN'/760, l='MpServer', x=-124.66, y=46.13, z=832.56], EntityItem['item.tile.waterKelpGiantGRN'/761, l='MpServer', x=-126.47, y=46.13, z=832.16], EntityItem['item.tile.gravel'/43770, l='MpServer', x=-129.94, y=25.13, z=811.81], EntityItem['item.item.dyePowder.black'/33538, l='MpServer', x=-185.84, y=65.13, z=789.34], EntityBat['Bat'/25349, l='MpServer', x=-171.50, y=33.10, z=845.50], EntityItem['item.tile.waterKelpGiantGRN'/787, l='MpServer', x=-105.72, y=50.13, z=777.25], EntityCreeper['Creeper'/214809, l='MpServer', x=-175.43, y=29.42, z=800.32], EntityKobold['Kobold'/276255, l='MpServer', x=-198.50, y=36.00, z=797.50], EntityBat['Bat'/4914, l='MpServer', x=-201.50, y=37.10, z=798.50], EntityItem['item.tile.gravel'/296752, l='MpServer', x=-104.53, y=16.66, z=764.50], EntityBat['Bat'/4917, l='MpServer', x=-171.25, y=36.10, z=808.53], EntitySquid['Squid'/3898, l='MpServer', x=-119.64, y=48.38, z=811.16], EntityZombie['Zombie'/30523, l='MpServer', x=-196.66, y=28.00, z=823.31], EntityZombie['Zombie'/30524, l='MpServer', x=-169.84, y=28.00, z=795.72], EntitySquid['Squid'/45884, l='MpServer', x=-208.53, y=60.00, z=789.53], EntitySpider['Spider'/101189, l='MpServer', x=-167.50, y=36.00, z=796.50], EntityItem['item.tile.torch'/28488, l='MpServer', x=-183.17, y=25.13, z=771.66], EntityHuman['DanTDM'/60254, l='MpServer', x=-176.47, y=32.00, z=814.94], EntityHuman['slowpoke101'/60255, l='MpServer', x=-200.11, y=28.00, z=821.71], EntityHuman['WayofFlowingTime'/60256, l='MpServer', x=-176.13, y=29.00, z=802.50], EntityCreeper['Creeper'/198501, l='MpServer', x=-182.08, y=34.00, z=811.71], EntityItem['item.tile.rail'/31600, l='MpServer', x=-172.34, y=9.13, z=886.81], EntityItem['item.tile.rail'/31601, l='MpServer', x=-173.09, y=9.13, z=884.75], EntityCreeper['Creeper'/68488, l='MpServer', x=-169.69, y=32.00, z=849.69], EntityErepede['Erepede'/109494, l='MpServer', x=-202.41, y=36.00, z=805.25], EntitySquid['Squid'/39864, l='MpServer', x=-180.11, y=52.30, z=777.57], EntityIka['Ika'/319425, l='MpServer', x=-140.77, y=55.00, z=791.23], EntityClientPlayerMP['P3rf3ct_Zer0'/1996, l='MpServer', x=-167.50, y=73.62, z=825.50], EntityHat['unknown'/1998, l='MpServer', x=-167.50, y=73.62, z=825.50], EntityHuman['Pahimar'/230361, l='MpServer', x=-179.09, y=26.00, z=853.50], EntityBat['Bat'/2016, l='MpServer', x=-170.30, y=29.76, z=797.37], EntityItem['item.item.dyePowder.black'/76795, l='MpServer', x=-208.45, y=60.13, z=789.65]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by DPxKnightxZero** [comment]
Its caused when scrolling the mouse wheel in NEI.

**Comment by DPxKnightxZero** [comment]
After you reach the end of the slots in infinite inventory the game crashes.

**Comment by Funwayguy** [comment]
What are your config settings so I can recreate this?

**Comment by DPxKnightxZero** [comment]
Here is the mods used to create the crash environment and such https://www.dropbox.com/sh/pmttjzjl5vecm58/AAAR_9Z8YgSNddxUlphls-QJa?dl=0

**Comment by DPxKnightxZero** [comment]
I included the exact version of all things I used to create the environment but if your looking for a more direct approach you can just join. http://www.technicpack.net/modpack/pz-project-zer0.741676 I will op you.
