### ISSUE TITLE
conflict  Galacticraft

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Funwayguy/EnviroMine#162]
disconnect from the server after installation AstroMiner
or ssp
http://paste.ubuntu.com/12827309/
[21:25:31] [Client thread/ERROR] [FML/]: A severe problem occurred during the spawning of an entity at ( -193.0,67.0, 280.0)
java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.planets.asteroids.entities.EntityAstroMiner.func_70302_i_(EntityAstroMiner.java:235) ~[EntityAstroMiner.class:?]
	at enviromine.handlers.RotHandler.rotInvo(RotHandler.java:81) ~[RotHandler.class:?]
	at enviromine.handlers.EM_EventManager.onEntityJoinWorld(EM_EventManager.java:156) ~[EM_EventManager.class:?]

**Comment by SvEgiiVEteR** [comment]
1.7-3.0.12.376
problem still exists. or even the author did not correct mod?
